telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "c:/projects/mybot/bot.py", line 35, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message khjl
root - INFO - User Earlinn, Chat id 331787003, Message ggg
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message куку
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message fgkhl
root - INFO - User Earlinn, Chat id 331787003, Message vl;
root - INFO - User Earlinn, Chat id 331787003, Message hh
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message dytfui
root - INFO - User Earlinn, Chat id 331787003, Message fgiuoh
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message апшщ
root - INFO - User Earlinn, Chat id 331787003, Message вкнеагнпш
root - INFO - User Earlinn, Chat id 331787003, Message че
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 56, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message start
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 56, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message Прислать котика
root - INFO - User Earlinn, Chat id 331787003, Message Прислать котика
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 54, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 117, in next_full_moon
    full_moon = ephem.next_full_moon(date)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\ephem\__init__.py", line 224, in next_full_moon
    return _find_moon_phase(date, twopi, pi)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\ephem\__init__.py", line 194, in _find_moon_phase
    d0 = Date(d0)
ValueError: your date string  does not look like a year/month/day optionally followed by hours:minutes:seconds
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 61, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
root - INFO - User Earlinn, Chat id 331787003, Message Созвездие Mars
root - INFO - User Earlinn, Chat id 331787003, Message Слова куку
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 61, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 61, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message gu
root - INFO - User Earlinn, Chat id 331787003, Message hl
root - INFO - User Earlinn, Chat id 331787003, Message tfuyig
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - INFO - User Earlinn, Chat id 331787003, Message fgjkl;hghjk
root - INFO - User Earlinn, Chat id 331787003, Message hkjl;
root - INFO - User Earlinn, Chat id 331787003, Message hjkl;
root - INFO - User Earlinn, Chat id 331787003, Message ghjkl
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 69, in planet
    planet, empty_date = user_input[1], 2
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
