telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\updater.py", line 332, in _network_loop_retry
    if not action_cb():
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\updater.py", line 293, in polling_action_cb
    allowed_updates=allowed_updates)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\bot.py", line 1983, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\utils\request.py", line 327, in post
    **urlopen_kwargs)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\utils\request.py", line 242, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 37, in planet_handler
    planet = planet[1]
IndexError: list index out of range
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 37, in planet_handler
    planet = planet[1]
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 37, in planet_handler
    planet = planet[1]
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 30, in greet_planet
    user_text = ephem.Mars('2019/03/03')
NameError: name 'ephem' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 30, in greet_planet
    user_text = ephem.Mars('2019/03/03')
NameError: name 'ephem' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 30, in planet
    user_text = ephem.Mars('2019/03/03')
NameError: name 'ephem' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Lisys\AppData\Roaming\Python\Python37\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 30, in planet
    user_text = ephem.Mars('2019/03/03')
NameError: name 'ephem' is not defined
